<?php

namespace Database\Seeders;

use App\Enums\ModulePermission;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Seeds all Spatie roles and permissions.
 * Must run FIRST — users and all other seeders depend on roles existing.
 *
 * Permissions are generated from `App\Enums\ModulePermission`, so every
 * module/ability pairing defined in `config/permissions.php` is kept in
 * sync automatically — there is no separate hardcoded permission list.
 */
class RolesAndPermissionsSeeder extends Seeder
{
    // ─── Role → Permission mapping ────────────────────────────────────────────

    private const ROLES = [
        'super_admin' => '*', // all permissions

        'staff' => [
            'access_dashboard',
            'view_campaigns', 'create_campaigns', 'edit_campaigns',
            'view_campaign_categories', 'create_campaign_categories', 'edit_campaign_categories',

            'view_meetings', 'create_meetings', 'edit_meetings', 'approve_meeting_minutes',

            'view_beneficiaries', 'create_beneficiaries', 'edit_beneficiaries',
            'view_sensitive_details_beneficiaries',
            'create_beneficiary_assessments',
            'create_aid_items', 'edit_aid_items',
            'create_beneficiary_supports',
            'view_beneficiary_support_reports', 'export_beneficiary_support_reports',
            'view_campaign_beneficiary_reports', 'export_campaign_beneficiary_reports',

            'view_accounts', 'create_accounts', 'edit_accounts',
            'view_transactions', 'create_transactions',
            'view_donations', 'export_donations',
            'view_general_expenses', 'create_general_expenses', 'edit_general_expenses', 'delete_general_expenses',
            'view_campaign_expenses', 'create_campaign_expenses', 'edit_campaign_expenses',
            'view_payment_methods', 'create_payment_methods', 'edit_payment_methods', 'delete_payment_methods',
            'view_general_expense_categories', 'create_general_expense_categories', 'edit_general_expense_categories', 'delete_general_expense_categories',
            'view_donor_profiles', 'create_donor_profiles', 'edit_donor_profiles', 'delete_donor_profiles',
            'view_transfers', 'create_transfers',

            'view_news', 'create_news', 'edit_news',
            'view_legal_documents', 'edit_legal_documents',
            'view_faqs', 'create_faqs', 'edit_faqs',
            'view_contact_messages', 'mark_reviewed_contact_messages', 'delete_contact_messages',
        ],

        'field_worker' => [
            'access_dashboard',
            'view_beneficiaries', 'create_beneficiaries',
            'view_sensitive_details_beneficiaries',
            'view_beneficiary_support_reports', 'view_campaign_beneficiary_reports',
            'create_beneficiary_assessments',
            'view_campaigns',
        ],

        'donor' => [
            'view_campaigns',
            'view_news',
        ],
    ];

    public function run(): void
    {
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // Create every permission generated by the ModulePermission enum
        $permissions = collect(ModulePermission::cases())
            ->flatMap(fn (ModulePermission $module) => $module->allPermissions())
            ->unique()
            ->values()
            ->mapWithKeys(fn (string $name) => [
                $name => Permission::firstOrCreate(['name' => $name, 'guard_name' => 'web']),
            ]);

        // Create roles and assign permissions
        foreach (static::ROLES as $roleName => $rolePermissions) {
            $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);

            if ($rolePermissions === '*') {
                $role->syncPermissions($permissions->values());
            } else {
                $role->syncPermissions(
                    $permissions->only($rolePermissions)->values()
                );
            }
        }

        $this->command->info('✅ Roles and permissions seeded.');
    }
}
